"""Does the gate pass a capture that *does* carry a V.90 upstream?

A gate that only ever fails is as useless as one that only ever passes. So a
well-formed 3200-baud raised-cosine upstream is put into a real capture, at the
carrier the receiver is told to expect and at the rate the transcript says was
negotiated, and the gate has to pass it. The same capture with that signal
absent has to fail, and the margin between the two is the gate's whole worth.
"""
import sys, wave
import numpy as np

sys.path.insert(0, "/home/cooper/softmodem/scripts/bench")

CAP = sys.argv[1]
OUT = sys.argv[2]
FS, SYM, CARRIER = 8000, 3200.0, 3200.0 * 4 / 7

with wave.open(CAP, "rb") as w:
    fs = w.getframerate()
    raw = np.frombuffer(w.readframes(w.getnframes()), dtype="<i2")
a = raw.reshape(-1, 2).astype(np.int16)
line = a[:, 0].astype(np.float64) / 32768.0
n = len(line)

# A 1280-point constellation at 3200 baud: symbols on a ring, 9 bits each at
# 28800 bit/s. Raised-cosine shaped, alpha = 0.3, oversampled to 8 kHz.
rng = np.random.default_rng(7)
L = 1280
# 3200 baud is 2.5 samples at 8 kHz, which cannot be generated by repeating
# samples -- the first version of this repeated by int(8000/3200) = 2 and
# quietly produced a 1600-baud signal, which the gate then could not see. So it
# is built at 16 kHz, where 3200 baud is exactly five samples, and decimated.
FS2 = 2 * FS
alpha = 0.3
n2 = 2 * n
nsym = n2 // 5 + 8
pts = np.exp(1j * (np.arange(L) * 2 * np.pi / L + rng.uniform(0, 2 * np.pi)))
sym = pts[rng.integers(0, L, nsym)]
up = np.zeros(n2)
up[: nsym * 5] = np.repeat(sym, 5)[: n2]
# Raised-cosine shaping, alpha = 0.3, at the 16 kHz rate.
F = np.fft.rfft(up)
fq = np.fft.rfftfreq(n2, 1 / FS2)
H = np.zeros_like(F)
band = (fq >= 0) & (fq <= SYM / 2 * (1 + alpha))
H[band] = 1 + np.sin(np.pi * fq[band] / (SYM * (1 + alpha))) / (1 + alpha)
shaped = np.fft.irfft(F * H, n2)
sig2 = np.real(shaped * np.exp(2j * np.pi * CARRIER * np.arange(n2) / FS2))
sig = sig2[::2][:n]                        # back to 8 kHz, 3200 baud intact
sig *= 0.05 / np.sqrt((sig ** 2).mean())

print(f"  synthetic upstream: {SYM:.0f} baud, alpha {alpha}, carrier {CARRIER:.2f} Hz,")
print(f"  {L}-point constellation, at {10*np.log10(np.sqrt((sig**2).mean())):.1f} dBFS")
# Two files, one with the synthetic upstream and one without: the gate has to
# pass the first and fail the second, and the margin between them is the point.
# "WITH" in "WITHOUT it" is true, which is how the first version of this wrote
# both to the same path and validated nothing.
for tag, add, p in (("with the signal", sig, OUT),
                   ("without it", 0.0 * sig, "/tmp/opencode/gate-none.wav")):
    ch0 = line + add
    b = np.column_stack([np.clip(ch0 * 32768, -32768, 32767).astype(np.int16), a[:, 1]])
    with wave.open(p, "wb") as w:
        w.setnchannels(2); w.setsampwidth(2); w.setframerate(FS)
        w.writeframes(b.tobytes())
    print(f"  wrote {tag} -> {p}")
